Numpy tutorial

In [4]:
import numpy as np

In [5]:
a=np.array([2,2,3,4])

In [6]:
# check array dimensions
a.ndim
a.itemsize #prints 8 ie int occupies 8 bytes coz am using 64 bit OS

8

In [7]:
a=np.array([[12,22],[32,11],[22,11]])
a.ndim  # 2-D array
a.dtype  #check the datatype

dtype('int64')

In [8]:
a=np.array([[12,22],[32,11],[22,11]], dtype=np.float64)  #change the arry to floats

In [9]:
a.itemsize

8

In [10]:
a

array([[12., 22.],
       [32., 11.],
       [22., 11.]])

In [11]:
# total number of elements
a.size
# shape
a.shape

(3, 2)

In [12]:
# initialize an array with zeros or ones ie 3 by 2 array
arr=np.zeros( (3,2) )
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# reshape the array to 2 by 3
arr.reshape(2,3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# flatten the array
arr.ravel()

array([0., 0., 0., 0., 0., 0.])

In [15]:
# define an array with arange function
arr=np.arange(0,5)  #note that 5 aint inclusive

In [16]:
arr

array([0, 1, 2, 3, 4])

In [17]:
# using linspace eg generate 10 numbers between 5 and 15  which are linearly spaced
np.linspace(5,15,10)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [18]:
ar=([[1,2],[3,4],[5,6]])
ar

[[1, 2], [3, 4], [5, 6]]

In [19]:
# find sqrt of every number
np.sqrt(ar)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [20]:
# find stardard deviation
np.std(ar)

1.707825127659933

iterating arrays

In [21]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# iterate through the array
for cell in arr.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [23]:
# alternatively use nditer function
# c order goes row  by row printing the values
for x in np.nditer(arr, order="C"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [24]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# Fortran way
for x in np.nditer(arr, order="F"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [26]:
# Fortran way
for x in np.nditer(arr, order="F", flags=["external_loop"]):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [27]:
# square every array element
for x in np.nditer(arr,op_flags=['readwrite']):
    x[...]=x*x
arr

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [28]:
arr

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [29]:
arrb=np.arange(3,15,4).reshape(3,1)
arrb

array([[ 3],
       [ 7],
       [11]])

In [30]:
# iterating through 2 arrays
# array broadcasting is possible if the arrays are equal of if one of the arrays is 1
for m,n in np.nditer([arr,arrb]):
    print(m,n)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


slicing, stacking, indexing arrays

In [31]:
arr1=np.array([[6,7,8],[1,2,3],[9,3,2]])
arr1

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [34]:
# print third element of second row
arr1[1,2]

3

In [39]:
# when slicing, last index aint included. arr1 will go from 0 to 1, then the second element
arr1[0:2,2]

array([8, 3])

In [40]:
# display last two columns
arr1[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [44]:
# stacking two arrays together
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [45]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [52]:
# vertical stacking
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [53]:
# horizontal stacking
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [55]:
# splitting an array
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [58]:
# split into 3 separate arrays
result=np.hsplit(a,3)

In [59]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [60]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [61]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [62]:
# you can as well split vertically
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [63]:
a[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
a[1]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
# extract elements greater than 5
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
y=x>5
y  #Show the values greater than 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [71]:
x[y]

array([ 6,  7,  8,  9, 10, 11])