Numpy tutorial

In [1]:
import numpy as np

In [14]:
a=np.array([2,2,3,4])

In [17]:
# check array dimensions
a.ndim
a.itemsize #prints 8 ie int occupies 8 bytes coz am using 64 bit OS

8

In [21]:
a=np.array([[12,22],[32,11],[22,11]])
a.ndim  # 2-D array
a.dtype  #check the datatype

dtype('int64')

In [26]:
a=np.array([[12,22],[32,11],[22,11]], dtype=np.float64)  #change the arry to floats

In [29]:
a.itemsize

8

In [30]:
a

array([[12., 22.],
       [32., 11.],
       [22., 11.]])

In [32]:
# total number of elements
a.size
# shape
a.shape

(3, 2)

In [52]:
# initialize an array with zeros or ones ie 3 by 2 array
arr=np.zeros( (3,2) )
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
# reshape the array to 2 by 3
arr.reshape(2,3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# define an array with arange function
arr=np.arange(0,5)  #note that 5 aint inclusive

In [55]:
arr

array([0, 1, 2, 3, 4])

In [56]:
# using linspace eg generate 10 numbers between 5 and 15  which are linearly spaced
np.linspace(5,15,10)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])