### K Fold Cross Validation
So far we have seen 2 training options.

1. Using all the data training and testing. eg give a kid 100 qns to train and ask the same questions
2. Splitting the data into training and testing data. eg give a kid 70 qns for training and the remaining 30 for testing.
3. Using K Fold Cross Validation method. Here, we evaluate the performance of different algorothms

In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
# import KFold classifier
from sklearn.model_selection import KFold

In [2]:
# we want to classify the digits dataset into one of the ten categories 0-9
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
# the issue with this is that you have to run it multiple times to make conclusions
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

#### we now use different classifiers and measure their performance

In [4]:
# Logistic regression
lr=LogisticRegression(solver="liblinear")
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.95

In [5]:
# Suport Vector Machine
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [6]:
# Random forest classifier
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9740740740740741

#### now lets do K Fold cross validation

In [7]:
# specify 3 folds
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
# using KFold on a dataset
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


How it is working. </br>
The dataset is divided into 3 folds.

1. first iteration has 1 fold for testing (0 1 2) and remaining 2 folds for training (3 4 5 6 7 8)
2. second iteration has (3 4 5) for testing and (0 1 2 6 7 8) for training
3. third iteration has (6 7 8) for testing and (0 1 2 3 4 5) for training

In [9]:
# lets write a method that takes madel, X_train, X_test, y_train, y_test as input and returns the model score
def get_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [10]:
# How the method works
get_score(SVC(),X_train, X_test, y_train, y_test)

0.9833333333333333

### now lets use kfold on our digits dataset

In [11]:
# StratifiedKFold is better than KFold in that it divides each of the classification categories in a uniform way
from sklearn.model_selection import StratifiedKFold

In [12]:
folds = StratifiedKFold(n_splits=3)

In [13]:
# prepare scores arrays
# This code simply explains how KFold cross validation work.
scores_lr = []
scores_svm = []
scores_rf = []

# lets use our ral dataset now
for train_index, test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]
    # le loop will iterate 3 times and it will take diff X_train,X_test,y_train,y_test measuring the performance of the model and then
    # append the scores to the defined arrays
    scores_lr.append(get_score(LogisticRegression(solver="liblinear"),X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))

#### what it did is iterate 3 times while appending the scores for each of the different values of X_train, X_test, y_train, y_test to the defines arrays

lets print the appended scores

In [14]:
# LogisticRegression
scores_lr

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [15]:
# SVC
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [16]:
# RandomForestClassifier
scores_rf

[0.9365609348914858, 0.9549248747913188, 0.9232053422370617]

#### The best way to archieve the above is to use cross_val_score method

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
# This takes the estimator(the ML model), X and y labels
# LogisticRegression()
cross_val_score(LogisticRegression(solver="liblinear"),digits.data,digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [19]:
# SVC
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [20]:
# RandomForestClassifier
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.90555556, 0.9637883 , 0.97493036, 0.92200557])

### Exercise
Use iris dataset to determine the best ML model based on performance; </br>

1. LogisticRegression
2. SVC
3. RandomForestClassifier
4. Decision Tree

use `cross_val_score` method to measure the performance of the best ML classifier

In [21]:
# import the required ML models and functions
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [22]:
# load the iris dataset
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [23]:
# define X and y labels
X = iris.data
y=iris.target

In [24]:
# split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [25]:
len(X_train), len(X_test)

(100, 50)

In [26]:
# LogisticRegression()
cross_val_score(LogisticRegression(solver="liblinear"),X_train,y_train)

array([0.9 , 0.95, 0.85, 1.  , 0.9 ])

In [27]:
# SVC
cross_val_score(SVC(),X_train,y_train)

array([1.  , 1.  , 1.  , 0.9 , 0.95])

In [28]:
# RandomForestClassifier
cross_val_score(RandomForestClassifier(),X_train,y_train)

array([1.  , 1.  , 1.  , 0.95, 0.95])

In [29]:
# Decision tree
cross_val_score(tree.DecisionTreeClassifier(),X_train,y_train)

array([1.  , 1.  , 1.  , 0.95, 0.8 ])